---
trigger: 
- main

pool:
  vmImage: 'ubuntu-22.04' 

stages:
- stage: Built
  displayName: Build using maven 
  jobs:
  - job: Build
    displayName: Maven Build
    steps:
    - task: Maven@4
      displayName: Maven JUnit Test
      inputs:
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true 
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
    - task: CopyFiles@2
      displayName: Copy the Build
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**/target/spring-petclinic-3.3.0-SNAPSHOT.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Build Artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Drop'



